name: Build

on:
  - push
  - pull_request
  - workflow_dispatch

jobs:
  Windows:
    runs-on: windows-2025
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 # needed for Nerdbank.GitVersioning

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Setup WSL2
      uses: Vampire/setup-wsl@v5
      with:
        distribution: Ubuntu-24.04

    - name: Setup SSH Server
      shell: wsl-bash {0}
      run: |
        apt-get update && apt-get upgrade -y
        apt-get install -y podman
        podman build -t renci-ssh-tests-server-image -f test/Renci.SshNet.IntegrationTests/Dockerfile test/Renci.SshNet.IntegrationTests/
        podman run --rm -h renci-ssh-tests-server -d -p 2222:22 renci-ssh-tests-server-image

    - name: Run Integration Tests .NET Framework
      run:
        dotnet test `
          -f net48 `
          --logger "console;verbosity=normal" `
          --logger GitHubActions `
          -p:CollectCoverage=true `
          -p:CoverletOutputFormat=cobertura `
          -p:CoverletOutput=..\..\coverlet\windows_integration_test_net_4_8_coverage.xml `
          test\Renci.SshNet.IntegrationTests\
